{% set version = '1.5.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-paran
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/paran_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/paran/paran_{{ version }}.tar.gz
  sha256: 7a089af1db4fb7ca13b588a106ce12725ce6ca6480289c5d7beeba5e07523435

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
  run:
    - r-base
    - r-mass

test:
  commands:
    - $R -e "library('paran')"           # [not win]
    - "\"%R%\" -e \"library('paran')\""  # [win]

about:
  home: https://cran.r-project.org/package=paran
  doc_url: http://alexisdinno.com/Software/files/PA_for_PCA_vs_FA.pdf
  license: GPL-2.0-only
  summary: An implementation of Horn's technique for numerically and graphically evaluating the
    components or factors retained in a principle components analysis (PCA) or common
    factor analysis (FA). Horn's method contrasts eigenvalues produced through a PCA
    or FA on a number of random data sets of uncorrelated variables with the same number
    of variables and observations as the experimental or observational data set to produce
    eigenvalues for components or factors that are adjusted for the sample error-induced
    inflation. Components with adjusted eigenvalues greater than one are retained. paran
    may also be used to conduct parallel analysis following Glorfeld's (1995) suggestions
    to reduce the likelihood of over-retention.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: paran
# Version: 1.5.2
# Date: 2018-10-14
# Title: Horn's Test of Principal Components/Factors
# Author: Alexis Dinno <alexis.dinno@pdx.edu>
# Maintainer: Alexis Dinno <alexis.dinno@pdx.edu>
# Depends: R (>= 1.8.0), MASS
# Description: An implementation of Horn's technique for numerically and graphically evaluating the components or factors retained in a principle components analysis (PCA) or common factor analysis (FA). Horn's method contrasts eigenvalues produced through a PCA or FA on a number of random data sets of uncorrelated variables with the same number of variables and observations as the experimental or observational data set to produce eigenvalues for components or factors that are adjusted for the sample error-induced inflation. Components with adjusted eigenvalues greater than one are retained. paran may also be used to conduct parallel analysis following Glorfeld's (1995) suggestions to reduce the likelihood of over-retention.
# URL: http://alexisdinno.com/Software/files/PA_for_PCA_vs_FA.pdf
# License: GPL-2
# LazyLoad: true
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2018-10-14 21:29:35 UTC; Alexis
# Repository: CRAN
# Date/Publication: 2018-10-14 23:30:03 UTC
